name: Release CI
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: semantic-release-config-gitmoji-module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
